language: node_js
node_js:
    - 9
notifications:
    email: false
    slack:
        secure: pFmdK7X7aHmsurcqy5C6B5yfBl6FBj7Pz8ncSdgWsjTP3lB2CSwUEoz632mEfA0ArE3Xmx0t+uxKGNvfVFNPoSzua3z+IMW+1855Ri3HINz939RarqHeJEN3YX+ePZw/SG885wGZoBExzngu1dNDkStSehdHZs8/8qiRYNkD1dtTGqTiZu03FEim8Of9sEIMdbaZK1j92tjCQucRSUX4lmLqoxTnJKlVneh67UwHC6mTddDwCTkbMLlVRz+OByGfPSuJ8vxJ4vQVX3dgSZ/E/AbTwQudrwnR04HNCYGkmmTboKlc83+BY6n6y9X8++ZajvnGBnaisHcqPUe3FNwVA9CEhYYHRNwkdQIrwFwXu706gphuinW4IJRSiX1y/PkuLjsw1nv0AVk9RiXwOfUKRfjNXvp2i1MnuT5raDu9E7bcnyvK5WDtJvi4A5j3OfXEsZ1LS58CVTwe4af2mZzj9wyR9MeMN+MCDN6hn/vDPJiqGJ7bl27+0T7Sw8nO1y0KF52GQJ9nzyukn73mDUo+aKr9HzsLrVVqr475SmYjciRe86dCSSlYfkbk16jIQv4d/bikkLMr3vHbYM3FNuv/5r7Q/z2ZDDfFiHd2kjoe2Hv/JSUcUla2YDLzEwQVgq0o7HXfCNE+Ah8JUkVICZiroFxzLWXOZW09pHgNmNFjNDk=
        on_pull_requests: false
