name = "onroads"
type = "webpack"
account_id = "b4bfdf5e220d6c0b22e39b54f8b59c96"
workers_dev = false
route = "test.onroads.xyz/*"
zone_id = "426b1ba897abc44f3b9fa527c0c13372"

[site]
bucket = "./public"
entry-point = "workers-site"
